# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Quantitative Insights 
author: Benjamin Rose
email: Ben_Rose@baylor.edu
copyright: 2024-2025
logo: book/data_analysis.001.png
exclude_patters: [README.md, LICENSE.txt, makefile]


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # execute_notebooks: force
  execute_notebooks: 'off'

html:
  home_page_in_navbar: false
  baseurl: https://github.com/benjaminrose/data-analysis-book
  # Add GitHub buttons to your book
  # See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
      <div>
          CC BY-NC 4.0 
      </div>

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: QuantitativeInsights.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - book/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/benjaminrose/data-analysis-book
  path_to_book: book
  branch: main
