# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Practical Data Analysis 
author: Benjamin Rose
email: Ben_Rose@baylor.edu
copyright: 2024-2025
logo: book/data_analysis.001.png


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # execute_notebooks: force
  execute_notebooks: 'off'

html:
  home_page_in_navbar: false
  # baseurl: benjaminrose.github.io/data-analysis-book
  # Add GitHub buttons to your book
  # See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
  # use_issues_button: true
  # use_repository_button: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: dataanalysis.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - book/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/benjaminrose/DataAnalysisBook  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

